### ISSUE TITLE
Kodi can only play from backend through ssh tunnel if tunnel is bound to 127.0.0.1

### ISSUE THREAD

**Issue by watercrossing** [janbar/pvr.mythtv#104]
I usually set the local port for my ssh tunnels to a specific loopback interface, for example `127.1.1.1:6543` and `127.1.1.1:6544` for mythtv.
This works fine for receiving metadata from the backend, but when I try to play a recording / livetv from the backend, the addon appears to try to connect to `127.0.0.1:6543` - which it obviously cannot do:
```
14:37:20.490 T:13496   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)Myth::LiveTVPlayback::SpawnLiveTV: trying recorder num (4) channum (104)
14:37:20.490 T:13496   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)Myth::ProtoBase::SendCommand: GET_RECORDER_FROM_NUM[]:[]4
14:37:20.542 T:13496   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)Myth::ProtoBase::RcvMessageLength: 18
14:37:20.542 T:13496   DEBUG: AddOnLog: MythTV PVR Client: (CPPMyth)Myth::ProtoMonitor::GetRecorderFromNum75: open recorder 4 (127.0.0.1:6543)
14:37:21.133 T:2912   DEBUG: AddOnLog: MythTV PVR Client: PVRClientMythTV::RunHouseKeeping
14:37:21.545 T:13496   ERROR: AddOnLog: MythTV PVR Client: (CPPMyth)__connectAddr: failed to connect (10061)
```
If I forward `127.0.0.1:6543` to the backend, everything works. 
So it appears that the address setting in the addon configuration gets ignored/overwritten?

**Comment by janbar** [comment]
The addon setting address is the IP of your master backend which controls the mythtv infrastructure. The infrastructure could contain some slave servers with their source capture cards and their recording storage. Asking a recorder to playback a live or a recording source , the backend returns the IP address of server to connect to: the master itself or a slave.
The configured address in backend settings should the address of the interface where remote can connect to the backend. It shouldn't the loopback address, because this address will be forwarded to client asking for recorder or playback source. If the loopback address is set then only local programs (frontend or kodi) will succeeded to playback live or recording.
I you want to allow remote host to connect to your backend then you have to configure (in the backend setting) an address of the accessible interface for remotes.
I never experienced vpn , so I have no idea how to resolve your case.

**Comment by watercrossing** [comment]
Ah, thank you - I did not consider the potential for slave servers in the environment. I guess the only solution that would work in my situation is to use hostnames instad of ip addresses, and have those resolve differently when tunneling.
