### ISSUE TITLE
Channel icons not updating

### ISSUE THREAD

**Issue by meatychunks99** [janbar/pvr.mythtv#206]
Kodi 19.5
Mythtv 32

Updated icons on Mythtv are available via the API http://<backend>:6544/Channel/GetChannelInfoList
However, the icons are not showing on the Kodi frontend. I've deleted the Textures.db file as suggested in the most recent post on this list, but that succeeded in only removing the existing old icons on the frontend.

**Comment by janbar** [comment]
First: Test the icons availabilities
- run in a Interner Browser the api: http://:6544/Channel/GetChannelInfoList
- copy one IconURL of your choice, then run api: http://:6544/{The Icon URI} to test Icon availability
- If the icon cannot be downloaded, then the issue is in your backend configuration. See note 1 below...

Second: If the tested icon can be downloaded with a browser, then try to trigger a channel update:
- In Kodi, go to channel screen, then click right on a channel and choose item "Trigger channels update".

Note 1: As specified in the MythTV documentation, the channel icon configured in channels setup (mythtv-setup or bd or http://:6544) cannot be a path. It MUST be only a file name of the icon stored in the home of the mythtv owner in: ".mythtv/channels/". You could use mythtv-setup to fix the issue or update manually the database or use the web frontend (http://:6544) to update the channel icon fields. After updating channel icons, you have to restart the backend to force reloading of its cache.

Note 2: From Kodi 18, the addon no longer handles the icons downloads, but lets Kodi to manage them. So the addon only forwards the URL of channel icons to Kodi. Time to live and refreshing of icon files are managed by Kodi itself. Obviously the icon URLs must be valid as it is tested at the first point.

**Comment by janbar** [comment]
Testing to trigger channel update, no longer refresh channel icons if their names haven't changed. Seems Kodi PVR doesn't handle a TTL or something like that.
~~The channel icons url (the file name), must be changed if you want to refresh icons.  So we cannot reuse an existing file name if its content has changed. We can add an index to the filename or use an abstract name.~~
The id of the icon URLs is the channel id. So URLs doesn't changed on icons update.

**Comment by meatychunks99** [comment]
Hi,
The mythtv database records are valid, with a file name only. Expected behaviour is that the icons appear in Mythweb, which they do.
I've checked and confirmed that the icons are available via the API URL. I've also tried the 'Trigger channels update' option with no success.
So published URLS are valid, and icons are available.
As for the filenames, I've added icons where some were previously missing, updated some icons with new file names, and some have retained the old file names. However, none of the icons for the 184 channels I have available are showing on the Kodi frontend.

**Comment by meatychunks99** [comment]
Just checked the debug log when running 'Trigger Channels Update':
`2023-02-27 10:58:26.584 T:10318   ERROR <general>: CCurlFile::Open failed with code 404 for http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=21501&Width=300:
                                                   
2023-02-27 10:58:26.584 T:10318   ERROR <general>: CFileCache::Open - <http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=21501&Width=300> failed to open
2023-02-27 10:58:26.584 T:10318   DEBUG <general>: CFileCache::Open - <http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=10110&Width=300> opening
2023-02-27 10:58:26.584 T:10318   DEBUG <general>: CurlFile::Open(0x7f6b440dfeb0) http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=10110&Width=300
`
The 'Width' parameter added to the URL results in a 404 - I've confirmed this in the browser. However, the initial error message places a ':' character at the end of the URL - when this is added to the URL in the browser, the icon is returned.

**Comment by ksooo** [comment]
If you use Nexus, go to settings / pvr & live tv / channels / channel manager. There you will find a button „recreate channel icons“.

**Comment by meatychunks99** [comment]
@ksooo - currently on Matrix...

**Comment by ksooo** [comment]
Then you should switch to the latest supported Kodi version which is Nexus. There will be no fixes for Kodi Matrix because it is eol.

**Comment by meatychunks99** [comment]
@ksooo OK - just ran the upgrade.
Tried 'recreate channel icons' as you suggested, but same result.
The debug log shows references to the icon URLS as per my previous post - with the Width attribute but no trailing ':' character, the URL returns a 404.
`GetImageHash - unable to stat url http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=10106&Width=300`
http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=10106&Width=300: returns an icon
http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=10106 returns an icon
http://192.168.2.200:6544/Guide/GetChannelIcon?ChanId=10106&Width=300 returns a 404

**Comment by meatychunks99** [comment]
OK - Solved. Little bit of digging on the mythtv forums, and the reason the URLS with the width and/or height params is failing is because mythtv needs write access to the channel folder to write the resized images.
Thanks for your input.

**Comment by janbar** [comment]
Great ! Sure the backend needs write permission to create icon with requested size.

**Comment by janbar** [comment]
> If you use Nexus, go to settings / pvr & live tv / channels / channel manager. There you will find a button „recreate channel icons“.

That is the graal to solve issue on icons. Thanks
