### ISSUE TITLE
Problem with recording resumepoints caused by inconsistent airdate

### ISSUE THREAD

**Issue by fetzerch** [janbar/pvr.mythtv#37]
Hi Janbar,

I hope you're doing well! The addon is still working perfectly here and it's used almost every day! Nice job you did with wsapi and cppmyth!

I've spend some time to track down a problem, but I'm unsure how to fix it, hence no PR yet. The symptom is that recording resumepoints (kodi videodatabase) are not set/shown when the recording is new (unwatched).

To reproduce: 
- play a recording, seek, stop playback --> no resumepoint is down, the recording is unwatched
- play it again, seek, stop playback --> resumepoint is saved and playback can be resumed.

The issue is caused by an inconsistency in the airdate field, which is filled into year, handed over to kodi and here used to identify a recording (`PVRRecordingsPath.cpp`). When the list of recordings is initially filled, the data is taken from the wsapi and the Airdate field is correctly field (for example with `2016-01-01`). When you start playing the recording, the addon receives a `RECORDING_LIST_CHANGE UPDATE` event where the airdate field of the ProgramInfo is set to the current date time. I've double checked with wireshark that it's not a parsing problem. This causes the recording to be transferred to Kodi with year set to -1. When you now stop the playback, Kodi sets the resumepoint for an incorrect path. When you start the playback again, and stop it, it will work because the path now doesn't contain a year anymore.

Have you seen this behaviour? Could you try to reproduce it? Would be good to know if that's some local issue with my setup. How would we fix that in the addon? As a workaround I patched out saving the year, but that's not the solution.

BTW: Has there been any progress on storing the resume points again on the backend? Or still not possible with wsapi? 

Ping also @metaron-uk who added that code in https://github.com/janbar/pvr.mythtv/commit/882370462b20d14d7465d1ca07ff5ba8d1e0b2ed. 

MythTV version: 0.28.0+fixes.20160506.0b08cb4-0ubuntu0mythbuntu2

Thanks much,
Christian

**Comment by metaron-uk** [comment]
Sounds like a bug / something I overlooked when adding my code.
Will try to find some time to investigate next week.

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by janbar** [comment]
Hi Christian, hope you are fine. Thanks for reporting this new issue. I hadn't care about this problem, but now reading you explaination I understand why sometimes I seen the same problem.
If the myth protocol `RECORDING_LIST_CHANGE` send different air date for a recording, I can suppose there is no possible fix to keep same path in kodi. The only way could be to no longer field the air date.
@metaron-uk, is it an issue for you to no longer field the air date ?

**Comment by janbar** [comment]
I will have a look on last change of the api 0.28 to manage resume point in backend. I will let you know.

**Comment by janbar** [comment]
Christian, I just explored the latest myth services api and no more service is available to set/get bookmark. Also we need to set/get with time position and probably I would have to propose a PR to mythtv sources like I done before for EDL. Unfortunately I have no time to do it and the proposed change would be only included in the next major release of MythTV. So the easier way to fix it seems to no longer fill the air date for recordings.

**Comment by janbar** [comment]
@metaron-uk , I think a workaround is possible by copying the previous air date on an recording update from the protocol. So the original air date, which is gathered by ws api, will keep unchanged.
In https://github.com/janbar/pvr.mythtv/blob/doityourself/src/pvrclient-mythtv.cpp#L426 , I already done a sort of this workaround to keep some video properties. To be tested ...

**Comment by metaron-uk** [comment]
Sorry to take so long to look into this. We got a new pet kitten on Tuesday and it rather monopolized my free time ;-).

> @metaron-uk, is it an issue for you to no longer field the air date ?

I added 'original airdate' in order to make scraping movies from the pvr:// protocol source work better.
By including 'year' in the filename, tmdb should have been able to do a better job at identifying which version of a movie had been recorded (the 1956 version or the 2010 re-make). This is only as good as the listings source however... mine seems to prefer imdb years to tmdb years, so it doesn't always work out as I expect.
I'd like to keep it if possible (other listings providers may be better than mine), but if kept it ought to provide consistent data...

> If the myth protocol RECORDING_LIST_CHANGE send different air date for a recording, I can suppose there is no possible fix to keep same path in kodi.

This sounds like either:
1) a mythv bug (If the 'UPDATE' message incorrectly contains 'airdate' instead of 'original airdate' information), or 
2) a pvr.mythtv (or cppmyth?) bug (if it is mistakenly assuming 'airdate' should contain 'original airdate').

From memory it was easy to get confused which of these should actually be in the 'airdate' field when putting together the original change, especially as the mythtv field didn't seem to have an unambiguous name. In the end I just took the 'suck it and see' approach - my backend gave me 'original airdate', so that is the field I used. I didn't realize UPDATE might be providing the 'other' value via a different mechanism...

> @metaron-uk , I think a workaround is possible by copying the previous air date on an recording update from the protocol. So the original air date, which is gathered by ws api, will keep unchanged.
> In https://github.com/janbar/pvr.mythtv/blob/doityourself/src/pvrclient-mythtv.cpp#L426 , I already done a sort of this workaround to keep some video properties.

If it does turn out to be a mythtv bug, this sounds like the best way to proceed, at least until it gets fixed.

**Comment by janbar** [comment]
I back ported the workaround to Jarvis stream. @fetzerch , please let me know about fixing.

**Comment by metaron-uk** [comment]
@janbar: I confirmed the problem was present and that your fix works here (with 0.27 backend and latest Krypton based libreElec build with latest doityourself pvr.mythtv).

From the symptoms it sounds like a mythtv bug. I looked in the mythtv code and 'QDate()' is the default for a new programinfo object, so it looks like originalairdate isn't being copied into the programinfo field associated to the UPDATE event properly... But after 4 hours of trying I decided I don't have the time to find where to look, let alone to find what might be wrong!

Just in case someone over at mythtv knows where to look and cares to fix it, I logged this: https://code.mythtv.org/trac/ticket/12781#ticket

**Comment by fetzerch** [comment]
@janbar, @metaron-uk: Thanks a lot for investigating and the quick fix! This is probably the best solution possible at the moment. It's working fine here in krypton.

> I just explored the latest myth services api and no more service is available to set/get bookmark. Also we need to set/get with time position.

When only using Kodi frontends with a shared DB it's fine. So I don't see any reason at the moment to do spend any effort in this. But thanks for checking!

> From the symptoms it sounds like a mythtv bug. I looked in the mythtv code and 'QDate()' is the default for a new programinfo object, so it looks like originalairdate isn't being copied into the programinfo field associated to the UPDATE event properly... But after 4 hours of trying I decided I don't have the time to find where to look, let alone to find what might be wrong!
> 
> Just in case someone over at mythtv knows where to look and cares to fix it, I logged this: https://code.mythtv.org/trac/ticket/12781#ticket

Thanks! I also had a quick check in the MythTV sources and came to the same conclusion. Let's see if they find/fix it upstream.

**Comment by janbar** [comment]
Hi @fetzerch, hope you re fine. I reviewed last changes from mythtv api and new services to handle saved bookmark have been published. I will update the addon in the couple of weeks to handle saved bookmark in the backend. The feature will be re-available from MythTV 29. br.

**Comment by janbar** [comment]
@fetzerch , reviewing the history of backend sources, It seems these changes relating bookmark have been merged with 0.28. So I will provide them as soon as possible for krypton release.

**Comment by fetzerch** [comment]
@janbar Nice, thanks much, that's great to hear! Meanwhile I watch mostly on one TV, but still a nice to have feature I think :)

**Comment by fetzerch** [comment]
Maybe just one additional note for reference: After updating to 4.11.1, I had to remove the tv database (which I had on mysql). Otherwise it didn't show all recordings and those that were shown had incorrect watched markers in the ui.
