### ISSUE TITLE
Kodi Recordings view doesn't list anything

### ISSUE THREAD

**Issue by ericfont** [janbar/pvr.mythtv#43]
I can't say if this issue is with Kodi or this addon.  Things were working fine while I was on the previous manually downloaded Kodi Jarvis, but a couple days ago when I switched to the newly announced _Windows Store_ version of Kodi Jarvis, I started experiencing this problem:

If I go to TV->Recordings in Kodi, then I see a blank list:

![screenshot 44](https://cloud.githubusercontent.com/assets/6502474/18762316/3ce3dc1e-80d6-11e6-8966-18131361789f.png)

Which is strange because Kodi is clearly connected to the mythtv backend, since it indicates how much free space I have on the backend and since it lists recently recorded videos on Kodi's TV page (which I can access just fine) and since Kodi's Guide page works just fine.  I'm wondering if anyone else has experience this issue upon upgrading to the Windows Store version of Kodi Jarvis?

pvr.mythtv version 4.7.2
Windows 10
kodi Build 17.0-BETA2 Git:20160920-9998310-dirty

**Comment by ericfont** [comment]
admittedly, I'm on an old version of mythtv backend...I might need to upgrade: 

MythTV Version : ad97d24
MythTV Branch : fixes/0.27
Network Protocol : 77
Library API : 0.27.20141016-1

**Comment by janbar** [comment]
Hi, those kind of issue could be due to a bad character encoding during the transfer of the recording list from the backend. To check that you can try to query your backend with your browser using url below:
`http://your_backend_ip:6544/Dvr/GetRecordedList`
A bad character encoding in any string will break the XML response.
Else, you don't use Kodi Jarvis (which is stable release), but seems you use the unstable Kodi krypton. You should retry with the Kodi Jarvis (version 16).
