### ISSUE TITLE
Continually losing PIN code

### ISSUE THREAD

**Issue by Yippee38** [janbar/pvr.mythtv#50]
I'm using a MythTV backend (Mythbuntu) and a linux (OpenSUSE Leaf) Kodi frontend (Isengard).  The pvr.mythtv plugin keeps giving me an error message saying, "Failed to connect the API services of MythTV backend. Please check your PIN code or backend setup.  The PIN code has to be configured in your backend to allow connections.
Do you want to retry?"

I have found that removing the PIN code from the pvr.mythtv addon, then re-adding it and enabling the addon will fix the problem for a while.

BTW, I am using a PIN code of "0000".

**Comment by janbar** [comment]
Thanks to report the issue.
Have you check the settings file of the addon is writable ? The file is in user home at .kodi/userdata/addons_data/pvr.mythtv/.
Also you can check its content and confirm the pin value is configured as you have done from the setting screen.

**Comment by Yippee38** [comment]
I just checked and the settings.xml file was 744 (with my user as the owner and "users" as the group).  I changed it to 774.  The value is stored correctly for the PIN in the settings file.  Then again, the system is not giving me the problem right now.  I'll check it again when the problem recurs.

**Comment by janbar** [comment]
So the issue isn t related with your setting of the pin. But probably due to failure to connect your backend at kodi startup. Your network could be overloaded due to huge remote media scan or other bottlenek.
Trying to update settings of the addon will restart the negociation with the backend. It could explain why updating the pin code seems to help.

**Comment by janbar** [comment]
If you use wifi network you can try with a wired link.

**Comment by Yippee38** [comment]
I am using wired.

Although your logic is sound, it seems to me that retrying the settings (by selecting "Yes" when the error message asks if you want to retry) would eventually fix it, but it does not.  It also occurs when the frontend and backend have been running for some time.  For example, if I get it working today, when I go to watch a video tomorrow (or maybe a couple of days from now), I might get the message even though the frontend and backend have been running the entire time.

Do you think that there is any chance that leaving the PIN code as the default could somehow be causing the problem?  I was thinking about trying a non-default PIN code (not that it matters to me).

**Comment by Yippee38** [comment]
Here's something interesting.  I had to restart my frontend.  As soon as I did, I launched Kodi then started a video.  No problem.  About 3 minutes later, I got the error, but the video continued to play.  I selected "Yes" and it didn't come back.

Don't know if that's relevant, but it's weird.

**Comment by Yippee38** [comment]
I take that back. The error did come back.  The video kept playing, and I was able to play another, but the message did come back.

**Comment by janbar** [comment]
The pin code is required to retrieve some backend settings. So its check is done when necessary. That could occur at any time and it is not related with playback which uses an other protocol.
Only web api relates the pin code: get recording metadata, guide , schedules.
Your problem seems to be linked with issue in your backend. Probably the web service api doesn t  reply to addon request in time.
