### ISSUE TITLE
Build without Kodi source

### ISSUE THREAD

**Issue by ImNtReal** [janbar/pvr.mythtv#63]
Is it possible to build from the release tarballs without pulling the Kodi source?

**Comment by janbar** [comment]
Normally no. The released branches have to be compiled with the right version of kodi headers.
Only my branches named as "devel-#" have to be compiled without kodi, for convenient. So you can use them as you need. To refresh your copy of these branches you will need to reset with flag hard, because I push force my commit into.

**Comment by ImNtReal** [comment]
I was hoping to find a way to build without pulling the full Kodi source because I'm trying to create a package for the AUR which means end users will be building the package, and will all need to pull the latest released copy of Kodi source along with the pvr.mythtv source to build it. If I'm missing something, let me know, otherwise feel free to close this one out. Thanks for your response.
